apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb
  ports:
  - name: influxdb
    protocol: TCP
    port: 8086
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb-service
        image: influxdb-image
        ports:
        - name: influxdb
          containerPort: 8086
        volumeMounts:
        - name: influxdb-storage
          mountPath: "/var/lib/influxdb"
        imagePullPolicy: Never
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
           claimName: influxdb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

